# air configuration file
# see https://github.com/cosmtrek/air for more information

root = "."
tmp_dir = ".air"

[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = true
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true