version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - go-pkg:/go/pkg
      - go-build:/root/.cache/go-build
    command: sleep infinity
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
      - SERVER_PORT=8080
      - SERVER_ROOT=/workspace/uploads
      - SERVER_LOG_LEVEL=DEBUG
    ports:
      - "8080:8080"
      - "2345:2345"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  
  # Optional: Uncomment below configuration if database is needed in the future
  # db:
  #   image: postgres:13-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: put-file
  #   ports:
  #     - "5432:5432"

volumes:
  go-pkg:
  go-build:
  # postgres-data: